spring.application.name=Backend
server.port=${PORT:8080}

gemini.api.key=ENC(rvDtwcesZ1FUH892AwiLxMBlsz6cckto5NHZviVXGK22tVWgZhukfhW6z1a/uBTNie/CmTW+Y2dIHFnHTWgbVLz3Ff7PpDNwXaRnxtJmxNA=)

logging.level.com.project.Backend=DEBUG
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

